project:
  type: website
  output-dir: docs

website:
  title: Penguinops
  site-url: https://nrob536.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: indicators/index.qmd
        text: Indicators
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/nrob536
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/nrob536
        aria-label: LinkedIn
  page-footer:
    left: Copyright 2026 Nestor M. Robinson
    right:
      - text: Email
        href: mailto:robinson.biol@gmail.com

format:
  html:  
    theme:
      dark: [cyborg, dark-theme.css]
      light: [cosmo, light-theme.css]
    toc: true
    smooth-scroll: true

execute:
  freeze: auto
